server:
  port: 8088
  name: iQnoon-service
spring:
  application:
    name: iQnoon-service
#  cloud:
#    zookeeper:
#      connect-string: localhost:2181
  datasource:
    url: jdbc:mysql://localhost:3306/iqnoon?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root
    password: iqnoon
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  elasticsearch:
    username: iqnoon
    password: iqnoon
    uris:
      - 127.0.0.1:9200
      - localhost:9300
# mybatis-plus
mybatis-plus:
  type-aliases-package: com/thoth/iqnoon/entities
  mapper-locations:
    - classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: INPUT
      field-strategy: NOT_EMPTY
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  enable: true
  documents:
    -
      group: 3.X版本
      name: 接口签名
      locations: classpath:sign/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/home.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0
    enableDynamicParameter: false
    enableDebug: true
    enableOpenApi: false
    enableGroup: true
  cores: false
  production: false
  basic:
    enable: false
    username: admin
    password: iqnoon